/*
BuildingPro Suites REST API

The BuildingPro Suites REST API provides unified access to the resources and data within a BuildingPro Suites environment.<br> <br> This documentation corresponds to the next BuildingPro Suites release. For previous BuildingPro Suites releases, please refer to the matching REST API version below:<br><br>   BuildingPro Suites v14.2: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> BuildingPro Suites v14.1: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> BuildingPro Suites v14.0: [2.8.7](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.8.7/openapi.yaml)<br> BuildingPro Suites v13.2: [2.7.0](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.7.0/openapi.yaml)<br> BuildingPro Suites v13.1: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> BuildingPro Suites v13.0: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> BuildingPro Suites v12.1: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> BuildingPro Suites v12.0: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> [Preview Beta](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/heads/develop/openapi.yaml)<br>

API version: 2.10.4
Contact: hello@eliona.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the ApiKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKey{}

// ApiKey An API key
type ApiKey struct {
	// The key
	Key *string `json:"key,omitempty"`
	// Date until the key is valid
	ValidUntil NullableTime `json:"validUntil,omitempty"`
	// Does the key has write access
	WriteAccess NullableBool `json:"writeAccess,omitempty"`
}

// NewApiKey instantiates a new ApiKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKey() *ApiKey {
	this := ApiKey{}
	return &this
}

// NewApiKeyWithDefaults instantiates a new ApiKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyWithDefaults() *ApiKey {
	this := ApiKey{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ApiKey) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiKey) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ApiKey) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ApiKey) SetKey(v string) {
	o.Key = &v
}

// GetValidUntil returns the ValidUntil field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiKey) GetValidUntil() time.Time {
	if o == nil || IsNil(o.ValidUntil.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ValidUntil.Get()
}

// GetValidUntilOk returns a tuple with the ValidUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKey) GetValidUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValidUntil.Get(), o.ValidUntil.IsSet()
}

// HasValidUntil returns a boolean if a field has been set.
func (o *ApiKey) HasValidUntil() bool {
	if o != nil && o.ValidUntil.IsSet() {
		return true
	}

	return false
}

// SetValidUntil gets a reference to the given NullableTime and assigns it to the ValidUntil field.
func (o *ApiKey) SetValidUntil(v time.Time) {
	o.ValidUntil.Set(&v)
}

// SetValidUntilNil sets the value for ValidUntil to be an explicit nil
func (o *ApiKey) SetValidUntilNil() {
	o.ValidUntil.Set(nil)
}

// UnsetValidUntil ensures that no value is present for ValidUntil, not even an explicit nil
func (o *ApiKey) UnsetValidUntil() {
	o.ValidUntil.Unset()
}

// GetWriteAccess returns the WriteAccess field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiKey) GetWriteAccess() bool {
	if o == nil || IsNil(o.WriteAccess.Get()) {
		var ret bool
		return ret
	}
	return *o.WriteAccess.Get()
}

// GetWriteAccessOk returns a tuple with the WriteAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiKey) GetWriteAccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WriteAccess.Get(), o.WriteAccess.IsSet()
}

// HasWriteAccess returns a boolean if a field has been set.
func (o *ApiKey) HasWriteAccess() bool {
	if o != nil && o.WriteAccess.IsSet() {
		return true
	}

	return false
}

// SetWriteAccess gets a reference to the given NullableBool and assigns it to the WriteAccess field.
func (o *ApiKey) SetWriteAccess(v bool) {
	o.WriteAccess.Set(&v)
}

// SetWriteAccessNil sets the value for WriteAccess to be an explicit nil
func (o *ApiKey) SetWriteAccessNil() {
	o.WriteAccess.Set(nil)
}

// UnsetWriteAccess ensures that no value is present for WriteAccess, not even an explicit nil
func (o *ApiKey) UnsetWriteAccess() {
	o.WriteAccess.Unset()
}

func (o ApiKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if o.ValidUntil.IsSet() {
		toSerialize["validUntil"] = o.ValidUntil.Get()
	}
	if o.WriteAccess.IsSet() {
		toSerialize["writeAccess"] = o.WriteAccess.Get()
	}
	return toSerialize, nil
}

type NullableApiKey struct {
	value *ApiKey
	isSet bool
}

func (v NullableApiKey) Get() *ApiKey {
	return v.value
}

func (v *NullableApiKey) Set(val *ApiKey) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKey) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKey(val *ApiKey) *NullableApiKey {
	return &NullableApiKey{value: val, isSet: true}
}

func (v NullableApiKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
