/*
BuildingPro Suites REST API

The BuildingPro Suites REST API provides unified access to the resources and data within a BuildingPro Suites environment.<br> <br> This documentation corresponds to the next BuildingPro Suites release. For previous BuildingPro Suites releases, please refer to the matching REST API version below:<br><br>   BuildingPro Suites v14.2: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> BuildingPro Suites v14.1: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> BuildingPro Suites v14.0: [2.8.7](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.8.7/openapi.yaml)<br> BuildingPro Suites v13.2: [2.7.0](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.7.0/openapi.yaml)<br> BuildingPro Suites v13.1: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> BuildingPro Suites v13.0: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> BuildingPro Suites v12.1: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> BuildingPro Suites v12.0: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> [Preview Beta](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/heads/develop/openapi.yaml)<br>

API version: 2.10.4
Contact: hello@eliona.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the RoleResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleResource{}

// RoleResource Resource and resource permission for user roles
type RoleResource struct {
	// Path name of the role resource
	Path *string `json:"path,omitempty"`
	// Role has view permission for this resource
	ViewPermission NullableBool `json:"viewPermission,omitempty"`
	// Role has edit permission for this resource
	EditPermission NullableBool `json:"editPermission,omitempty"`
	// Role has manage permission for this resource
	ManagePermission NullableBool `json:"managePermission,omitempty"`
}

// NewRoleResource instantiates a new RoleResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleResource() *RoleResource {
	this := RoleResource{}
	var viewPermission bool = false
	this.ViewPermission = *NewNullableBool(&viewPermission)
	var editPermission bool = false
	this.EditPermission = *NewNullableBool(&editPermission)
	var managePermission bool = false
	this.ManagePermission = *NewNullableBool(&managePermission)
	return &this
}

// NewRoleResourceWithDefaults instantiates a new RoleResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleResourceWithDefaults() *RoleResource {
	this := RoleResource{}
	var viewPermission bool = false
	this.ViewPermission = *NewNullableBool(&viewPermission)
	var editPermission bool = false
	this.EditPermission = *NewNullableBool(&editPermission)
	var managePermission bool = false
	this.ManagePermission = *NewNullableBool(&managePermission)
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *RoleResource) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleResource) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *RoleResource) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *RoleResource) SetPath(v string) {
	o.Path = &v
}

// GetViewPermission returns the ViewPermission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoleResource) GetViewPermission() bool {
	if o == nil || IsNil(o.ViewPermission.Get()) {
		var ret bool
		return ret
	}
	return *o.ViewPermission.Get()
}

// GetViewPermissionOk returns a tuple with the ViewPermission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoleResource) GetViewPermissionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ViewPermission.Get(), o.ViewPermission.IsSet()
}

// HasViewPermission returns a boolean if a field has been set.
func (o *RoleResource) HasViewPermission() bool {
	if o != nil && o.ViewPermission.IsSet() {
		return true
	}

	return false
}

// SetViewPermission gets a reference to the given NullableBool and assigns it to the ViewPermission field.
func (o *RoleResource) SetViewPermission(v bool) {
	o.ViewPermission.Set(&v)
}

// SetViewPermissionNil sets the value for ViewPermission to be an explicit nil
func (o *RoleResource) SetViewPermissionNil() {
	o.ViewPermission.Set(nil)
}

// UnsetViewPermission ensures that no value is present for ViewPermission, not even an explicit nil
func (o *RoleResource) UnsetViewPermission() {
	o.ViewPermission.Unset()
}

// GetEditPermission returns the EditPermission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoleResource) GetEditPermission() bool {
	if o == nil || IsNil(o.EditPermission.Get()) {
		var ret bool
		return ret
	}
	return *o.EditPermission.Get()
}

// GetEditPermissionOk returns a tuple with the EditPermission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoleResource) GetEditPermissionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.EditPermission.Get(), o.EditPermission.IsSet()
}

// HasEditPermission returns a boolean if a field has been set.
func (o *RoleResource) HasEditPermission() bool {
	if o != nil && o.EditPermission.IsSet() {
		return true
	}

	return false
}

// SetEditPermission gets a reference to the given NullableBool and assigns it to the EditPermission field.
func (o *RoleResource) SetEditPermission(v bool) {
	o.EditPermission.Set(&v)
}

// SetEditPermissionNil sets the value for EditPermission to be an explicit nil
func (o *RoleResource) SetEditPermissionNil() {
	o.EditPermission.Set(nil)
}

// UnsetEditPermission ensures that no value is present for EditPermission, not even an explicit nil
func (o *RoleResource) UnsetEditPermission() {
	o.EditPermission.Unset()
}

// GetManagePermission returns the ManagePermission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoleResource) GetManagePermission() bool {
	if o == nil || IsNil(o.ManagePermission.Get()) {
		var ret bool
		return ret
	}
	return *o.ManagePermission.Get()
}

// GetManagePermissionOk returns a tuple with the ManagePermission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoleResource) GetManagePermissionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ManagePermission.Get(), o.ManagePermission.IsSet()
}

// HasManagePermission returns a boolean if a field has been set.
func (o *RoleResource) HasManagePermission() bool {
	if o != nil && o.ManagePermission.IsSet() {
		return true
	}

	return false
}

// SetManagePermission gets a reference to the given NullableBool and assigns it to the ManagePermission field.
func (o *RoleResource) SetManagePermission(v bool) {
	o.ManagePermission.Set(&v)
}

// SetManagePermissionNil sets the value for ManagePermission to be an explicit nil
func (o *RoleResource) SetManagePermissionNil() {
	o.ManagePermission.Set(nil)
}

// UnsetManagePermission ensures that no value is present for ManagePermission, not even an explicit nil
func (o *RoleResource) UnsetManagePermission() {
	o.ManagePermission.Unset()
}

func (o RoleResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if o.ViewPermission.IsSet() {
		toSerialize["viewPermission"] = o.ViewPermission.Get()
	}
	if o.EditPermission.IsSet() {
		toSerialize["editPermission"] = o.EditPermission.Get()
	}
	if o.ManagePermission.IsSet() {
		toSerialize["managePermission"] = o.ManagePermission.Get()
	}
	return toSerialize, nil
}

type NullableRoleResource struct {
	value *RoleResource
	isSet bool
}

func (v NullableRoleResource) Get() *RoleResource {
	return v.value
}

func (v *NullableRoleResource) Set(val *RoleResource) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleResource) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleResource(val *RoleResource) *NullableRoleResource {
	return &NullableRoleResource{value: val, isSet: true}
}

func (v NullableRoleResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
