/*
BuildingPro Suites REST API

The BuildingPro Suites REST API provides unified access to the resources and data within a BuildingPro Suites environment.<br> <br> This documentation corresponds to the next BuildingPro Suites release. For previous BuildingPro Suites releases, please refer to the matching REST API version below:<br><br>   BuildingPro Suites v14.2: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> BuildingPro Suites v14.1: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> BuildingPro Suites v14.0: [2.8.7](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.8.7/openapi.yaml)<br> BuildingPro Suites v13.2: [2.7.0](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.7.0/openapi.yaml)<br> BuildingPro Suites v13.1: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> BuildingPro Suites v13.0: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> BuildingPro Suites v12.1: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> BuildingPro Suites v12.0: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> [Preview Beta](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/heads/develop/openapi.yaml)<br>

API version: 2.10.4
Contact: hello@eliona.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AssetTypeCategoryProperty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetTypeCategoryProperty{}

// AssetTypeCategoryProperty A property for asset type categories
type AssetTypeCategoryProperty struct {
	// The unique name for this asset type category property
	Name        string              `json:"name"`
	Translation NullableTranslation `json:"translation,omitempty"`
	// ID of measurement unit
	UnitId NullableInt32 `json:"unitId,omitempty"`
}

type _AssetTypeCategoryProperty AssetTypeCategoryProperty

// NewAssetTypeCategoryProperty instantiates a new AssetTypeCategoryProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetTypeCategoryProperty(name string) *AssetTypeCategoryProperty {
	this := AssetTypeCategoryProperty{}
	this.Name = name
	return &this
}

// NewAssetTypeCategoryPropertyWithDefaults instantiates a new AssetTypeCategoryProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetTypeCategoryPropertyWithDefaults() *AssetTypeCategoryProperty {
	this := AssetTypeCategoryProperty{}
	return &this
}

// GetName returns the Name field value
func (o *AssetTypeCategoryProperty) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AssetTypeCategoryProperty) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AssetTypeCategoryProperty) SetName(v string) {
	o.Name = v
}

// GetTranslation returns the Translation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetTypeCategoryProperty) GetTranslation() Translation {
	if o == nil || IsNil(o.Translation.Get()) {
		var ret Translation
		return ret
	}
	return *o.Translation.Get()
}

// GetTranslationOk returns a tuple with the Translation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetTypeCategoryProperty) GetTranslationOk() (*Translation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Translation.Get(), o.Translation.IsSet()
}

// HasTranslation returns a boolean if a field has been set.
func (o *AssetTypeCategoryProperty) HasTranslation() bool {
	if o != nil && o.Translation.IsSet() {
		return true
	}

	return false
}

// SetTranslation gets a reference to the given NullableTranslation and assigns it to the Translation field.
func (o *AssetTypeCategoryProperty) SetTranslation(v Translation) {
	o.Translation.Set(&v)
}

// SetTranslationNil sets the value for Translation to be an explicit nil
func (o *AssetTypeCategoryProperty) SetTranslationNil() {
	o.Translation.Set(nil)
}

// UnsetTranslation ensures that no value is present for Translation, not even an explicit nil
func (o *AssetTypeCategoryProperty) UnsetTranslation() {
	o.Translation.Unset()
}

// GetUnitId returns the UnitId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetTypeCategoryProperty) GetUnitId() int32 {
	if o == nil || IsNil(o.UnitId.Get()) {
		var ret int32
		return ret
	}
	return *o.UnitId.Get()
}

// GetUnitIdOk returns a tuple with the UnitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetTypeCategoryProperty) GetUnitIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnitId.Get(), o.UnitId.IsSet()
}

// HasUnitId returns a boolean if a field has been set.
func (o *AssetTypeCategoryProperty) HasUnitId() bool {
	if o != nil && o.UnitId.IsSet() {
		return true
	}

	return false
}

// SetUnitId gets a reference to the given NullableInt32 and assigns it to the UnitId field.
func (o *AssetTypeCategoryProperty) SetUnitId(v int32) {
	o.UnitId.Set(&v)
}

// SetUnitIdNil sets the value for UnitId to be an explicit nil
func (o *AssetTypeCategoryProperty) SetUnitIdNil() {
	o.UnitId.Set(nil)
}

// UnsetUnitId ensures that no value is present for UnitId, not even an explicit nil
func (o *AssetTypeCategoryProperty) UnsetUnitId() {
	o.UnitId.Unset()
}

func (o AssetTypeCategoryProperty) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetTypeCategoryProperty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Translation.IsSet() {
		toSerialize["translation"] = o.Translation.Get()
	}
	if o.UnitId.IsSet() {
		toSerialize["unitId"] = o.UnitId.Get()
	}
	return toSerialize, nil
}

func (o *AssetTypeCategoryProperty) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetTypeCategoryProperty := _AssetTypeCategoryProperty{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssetTypeCategoryProperty)

	if err != nil {
		return err
	}

	*o = AssetTypeCategoryProperty(varAssetTypeCategoryProperty)

	return err
}

type NullableAssetTypeCategoryProperty struct {
	value *AssetTypeCategoryProperty
	isSet bool
}

func (v NullableAssetTypeCategoryProperty) Get() *AssetTypeCategoryProperty {
	return v.value
}

func (v *NullableAssetTypeCategoryProperty) Set(val *AssetTypeCategoryProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetTypeCategoryProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetTypeCategoryProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetTypeCategoryProperty(val *AssetTypeCategoryProperty) *NullableAssetTypeCategoryProperty {
	return &NullableAssetTypeCategoryProperty{value: val, isSet: true}
}

func (v NullableAssetTypeCategoryProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetTypeCategoryProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
