/*
BuildingPro Suites REST API

The BuildingPro Suites REST API provides unified access to the resources and data within a BuildingPro Suites environment.<br> <br> This documentation corresponds to the next BuildingPro Suites release. For previous BuildingPro Suites releases, please refer to the matching REST API version below:<br><br>   BuildingPro Suites v14.2: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> BuildingPro Suites v14.1: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> BuildingPro Suites v14.0: [2.8.7](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.8.7/openapi.yaml)<br> BuildingPro Suites v13.2: [2.7.0](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.7.0/openapi.yaml)<br> BuildingPro Suites v13.1: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> BuildingPro Suites v13.0: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> BuildingPro Suites v12.1: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> BuildingPro Suites v12.0: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> [Preview Beta](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/heads/develop/openapi.yaml)<br>

API version: 2.10.4
Contact: hello@eliona.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// AssetIdentifyBy the model 'AssetIdentifyBy'
type AssetIdentifyBy string

// List of AssetIdentifyBy
const (
	ASSET_IDENTIFY_BY_RESOURCE_ID AssetIdentifyBy = "resourceId"
	ASSET_IDENTIFY_BY_DEVICE_ID   AssetIdentifyBy = "deviceId"
	ASSET_IDENTIFY_BY_ID          AssetIdentifyBy = "id"
	ASSET_IDENTIFY_BY_GAI_SITE_ID AssetIdentifyBy = "gai-siteId"
)

// All allowed values of AssetIdentifyBy enum
var AllowedAssetIdentifyByEnumValues = []AssetIdentifyBy{
	"resourceId",
	"deviceId",
	"id",
	"gai-siteId",
}

func (v *AssetIdentifyBy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AssetIdentifyBy(value)
	for _, existing := range AllowedAssetIdentifyByEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AssetIdentifyBy", value)
}

// NewAssetIdentifyByFromValue returns a pointer to a valid AssetIdentifyBy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAssetIdentifyByFromValue(v string) (*AssetIdentifyBy, error) {
	ev := AssetIdentifyBy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AssetIdentifyBy: valid values are %v", v, AllowedAssetIdentifyByEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AssetIdentifyBy) IsValid() bool {
	for _, existing := range AllowedAssetIdentifyByEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AssetIdentifyBy value
func (v AssetIdentifyBy) Ptr() *AssetIdentifyBy {
	return &v
}

type NullableAssetIdentifyBy struct {
	value *AssetIdentifyBy
	isSet bool
}

func (v NullableAssetIdentifyBy) Get() *AssetIdentifyBy {
	return v.value
}

func (v *NullableAssetIdentifyBy) Set(val *AssetIdentifyBy) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetIdentifyBy) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetIdentifyBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetIdentifyBy(val *AssetIdentifyBy) *NullableAssetIdentifyBy {
	return &NullableAssetIdentifyBy{value: val, isSet: true}
}

func (v NullableAssetIdentifyBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetIdentifyBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
